//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YonkerHN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int productoID { get; set; }
        public string nombrepro { get; set; }
        public int precio { get; set; }
        public int yonkerID { get; set; }
        public int categoriaID { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Yonker Yonker { get; set; }
    }
}
