//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YonkerHN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonkers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yonkers()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public int YonkerId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Products Products { get; set; }
    }
}
